version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest-rootless
    environment:
      - USER_UID="${UID}"
      - USER_GID="${GID}"
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - "DB_PASSWD=${DB_PW}"
    restart: always
    networks:
      - gitea
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"
    depends_on:
      - db
  db:
    image: postgres:9.6
    restart: always
    networks:
      - gitea
    environment:
      - POSTGRES_USER=gitea
      - "POSTGRES_PASSWORD=${DB_PW}"
      - POSTGRES_DB=gitea
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
