---
- name: Configure Ubuntu VMs
  hosts: ubuntu
  become: true
  tasks:

    - name: Create deployer user
      ansible.builtin.user:
        name: deployer
        state: present
        password: '!' # this is an invalid password hash, so password login is impossible

    - name: Add local SSH keys
      ansible.posix.authorized_key:
        user: deployer
        state: present
        key: "{{ lookup('file', './local_keyfile') }}"

    - name: Add sudoer file
      community.general.sudoers:
        name: deployer-sudo
        user: deployer
        commands: ALL
        state: present
        nopassword: true

    - name: Set Hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"

    - name: Create new network plan with Netplan
      ansible.builtin.template:
        src: netplan.yml.j2
        dest: /etc/netplan/99-local.yaml
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Create Script to Restart Network
      ansible.builtin.copy:
        src: reset-network.sh
        dest: /tmp/reset-network.sh
        owner: root
        group: root
        mode: '0744'
        backup: yes

# Thanks to the following for the upcoming trickery:
# https://unix.stackexchange.com/a/655691
# https://stackoverflow.com/a/61299910
# https://www.reddit.com/r/ansible/comments/mmcx8l/comment/gtrbuvj/
# and the Ansible docs

    - name: Restart networking
      ansible.builtin.command: /bin/sh /tmp/reset-network.sh
      async: 300
      poll: 0
      register: reset_ip

    - name: Change Ansible IP Address
      ansible.builtin.set_fact:
        ansible_host: "{{ lan_ip }}"

    - name: Reconnect
      ansible.builtin.async_status:
        jid: "{{ reset_ip.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30
      delay: 5
