network:
  version: 2
  renderer: 'networkd'
  ethernets:
    ens160:
      dhcp4: false
      addresses: ['10.0.6.11/24']
      nameservers:
        addresses:
          - '10.0.6.1'
          - '10.0.6.2'
          - '10.0.6.3'
      routes:
        - to: default
          via: 10.0.6.1
          metric: 100
          on-link: true
